[settings]
legacy_version_file = true
idiomatic_version_file_enable_tools = ["node", "terraform", "yarn"]

[tools]
actionlint = "latest"
bun = "latest"
deno = "latest"
go = "latest"
node = "24"
"github:anomalyco/opencode" = { version = "latest", asset_pattern = "opencode-darwin-arm64.zip" }
